// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOCSTFPW7Jt7Mcd6sTMSFDPHQcslMSEVQ',
    appId: '1:280005604016:web:80b986898a4ca57a564175',
    messagingSenderId: '280005604016',
    projectId: 'travel-768d0',
    authDomain: 'travel-768d0.firebaseapp.com',
    storageBucket: 'travel-768d0.firebasestorage.app',
    measurementId: 'G-MJWC7B7F48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Kxg8JBWMFyQQb6F5I414Wan6R2eCM5o',
    appId: '1:280005604016:android:4972d6198d78bbc7564175',
    messagingSenderId: '280005604016',
    projectId: 'travel-768d0',
    storageBucket: 'travel-768d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCys1jFz7o12yQslB2LKyVTCuDZINLPMJw',
    appId: '1:280005604016:ios:babb66c9fbfca4f5564175',
    messagingSenderId: '280005604016',
    projectId: 'travel-768d0',
    storageBucket: 'travel-768d0.firebasestorage.app',
    iosBundleId: 'com.example.vijeesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCys1jFz7o12yQslB2LKyVTCuDZINLPMJw',
    appId: '1:280005604016:ios:babb66c9fbfca4f5564175',
    messagingSenderId: '280005604016',
    projectId: 'travel-768d0',
    storageBucket: 'travel-768d0.firebasestorage.app',
    iosBundleId: 'com.example.vijeesh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOCSTFPW7Jt7Mcd6sTMSFDPHQcslMSEVQ',
    appId: '1:280005604016:web:73885c981a96e0ae564175',
    messagingSenderId: '280005604016',
    projectId: 'travel-768d0',
    authDomain: 'travel-768d0.firebaseapp.com',
    storageBucket: 'travel-768d0.firebasestorage.app',
    measurementId: 'G-1N3DY7ZP1D',
  );

}